### ISSUE TITLE
Lambdakiq jobs no longer work on rails 7.2

### ISSUE THREAD

**Issue by thenano** [rails-lambda/lambdakiq#36]
The job enqueuing fails with
```
undefined method `enqueue_after_transaction_commit?' for an instance of ActiveJob::QueueAdapters::LambdakiqAdapter
```
I have created the following pull request to address this: https://github.com/rails-lambda/lambdakiq/pull/35

**Comment by metaskills** [comment]
Thank you! Merged, going to do a gem update now too.

**Comment by thenano** [comment]
Amazing! thank you so much @metaskills

**Comment by thenano** [comment]
@metaskills I have just upgrade my app to 2.3.0 and can confirm it works with rails 7.2
